#############################################################################
# Makefile for building: Telli_IVI_GUI
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  Telli_IVI_GUI.pro
# Template: app
# Command: /usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/qmake -o Makefile Telli_IVI_GUI.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) --sysroot=/usr/local/qt_append/sysroots/aarch64-telechips-linux -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) --sysroot=/usr/local/qt_append/sysroots/aarch64-telechips-linux -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -isystem /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I. -I. -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Telli_IVI_GUI1.0.0
DISTDIR = /home/j/work/qt-navi/d3-navi/.tmp/Telli_IVI_GUI1.0.0
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) --sysroot=/usr/local/qt_append/sysroots/aarch64-telechips-linux -Wl,-O1 -Wl,-rpath-link,/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib
LIBS          = $(SUBLIBS) -lQt5MultimediaWidgets -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Sql -lsqlite3 -lQt5Core -lGLESv2 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
SED           = sed
STRIP         = $(OE_QMAKE_STRIP)

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = account/accountselectpage.cpp \
		aircon_page.cpp \
		ambient_page.cpp \
		ambient_preview.cpp \
		db/db.cpp \
		headlamp_page.cpp \
		home_page.cpp \
		main.cpp \
		mainwindow.cpp \
		maincontainer.cpp \
		music_page.cpp \
		notificationbanner.cpp \
		ripplewidget.cpp \
		settings_page.cpp \
		trunk_page.cpp \
		update_handler.cpp \
		video_page.cpp \
		window_page.cpp \
		mapview.cpp \
		navi_page.cpp \
		navi_utils.cpp qrc_resources.cpp \
		moc_accountselectpage.cpp \
		moc_ambient_preview.cpp \
		moc_mainwindow.cpp \
		moc_maincontainer.cpp \
		moc_notificationbanner.cpp \
		moc_ripplewidget.cpp \
		moc_mapview.cpp
OBJECTS       = accountselectpage.o \
		aircon_page.o \
		ambient_page.o \
		ambient_preview.o \
		db.o \
		headlamp_page.o \
		home_page.o \
		main.o \
		mainwindow.o \
		maincontainer.o \
		music_page.o \
		notificationbanner.o \
		ripplewidget.o \
		settings_page.o \
		trunk_page.o \
		update_handler.o \
		video_page.o \
		window_page.o \
		mapview.o \
		navi_page.o \
		navi_utils.o \
		qrc_resources.o \
		moc_accountselectpage.o \
		moc_ambient_preview.o \
		moc_mainwindow.o \
		moc_maincontainer.o \
		moc_notificationbanner.o \
		moc_ripplewidget.o \
		moc_mapview.o
DIST          = account/account_daddy.json \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Telli_IVI_GUI.pro account/accountselectpage.h \
		account/random_compat.h \
		aircon_page.h \
		ambient_page.h \
		ambient_preview.h \
		db/db.h \
		headlamp_page.h \
		home_page.h \
		mainwindow.h \
		maincontainer.h \
		music_page.h \
		notificationbanner.h \
		ripplewidget.h \
		settings_page.h \
		trunk_page.h \
		update_handler.h \
		video_page.h \
		window_page.h \
		mapview.h \
		navi_page.h \
		navi_utils.h account/accountselectpage.cpp \
		aircon_page.cpp \
		ambient_page.cpp \
		ambient_preview.cpp \
		db/db.cpp \
		headlamp_page.cpp \
		home_page.cpp \
		main.cpp \
		mainwindow.cpp \
		maincontainer.cpp \
		music_page.cpp \
		notificationbanner.cpp \
		ripplewidget.cpp \
		settings_page.cpp \
		trunk_page.cpp \
		update_handler.cpp \
		video_page.cpp \
		window_page.cpp \
		mapview.cpp \
		navi_page.cpp \
		navi_utils.cpp
QMAKE_TARGET  = Telli_IVI_GUI
DESTDIR       = 
TARGET        = Telli_IVI_GUI


first: all
####### Build rules

$(TARGET): ui_accountselectpage.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Telli_IVI_GUI.pro /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Telli_IVI_GUI.pro \
		resources.qrc \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5MultimediaWidgets.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Multimedia.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Widgets.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Gui.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Network.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Sql.prl \
		/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Telli_IVI_GUI.pro
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/features/lex.prf:
Telli_IVI_GUI.pro:
resources.qrc:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5MultimediaWidgets.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Multimedia.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Widgets.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Gui.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Network.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Sql.prl:
/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Telli_IVI_GUI.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents account/accountselectpage.h account/random_compat.h aircon_page.h ambient_page.h ambient_preview.h db/db.h headlamp_page.h home_page.h mainwindow.h maincontainer.h music_page.h notificationbanner.h ripplewidget.h settings_page.h trunk_page.h update_handler.h video_page.h window_page.h mapview.h navi_page.h navi_utils.h $(DISTDIR)/
	$(COPY_FILE) --parents account/accountselectpage.cpp aircon_page.cpp ambient_page.cpp ambient_preview.cpp db/db.cpp headlamp_page.cpp home_page.cpp main.cpp mainwindow.cpp maincontainer.cpp music_page.cpp notificationbanner.cpp ripplewidget.cpp settings_page.cpp trunk_page.cpp update_handler.cpp video_page.cpp window_page.cpp mapview.cpp navi_page.cpp navi_utils.cpp $(DISTDIR)/
	$(COPY_FILE) --parents account/accountselectpage.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		images/Settings_neon.png \
		images/Navi_neon.png \
		images/OFF_OFF.png \
		images/Headlamp.png \
		images/Window_neon.png \
		images/Checkbox_on.png \
		images/LOW_OFF.png \
		images/Navi_pos.png \
		images/account_background.png \
		images/Music_neon.png \
		images/AMBIENT_RED_OFF.png \
		images/MEDIUM_ON.png \
		images/prior.png \
		images/play.png \
		images/OFF_ON.png \
		images/Navi_home.png \
		images/Music.png \
		images/bg_thunder.png \
		images/sound.png \
		images/media_page_backgound.png \
		images/WINDOW_CLOSE.png \
		images/trash.png \
		images/AMBIENT_ON_OFF.png \
		images/AMBIENT_GREEN_OFF.png \
		images/bg_city.png \
		images/AMBIENT_GREEN_ON.png \
		images/bg_darkwave.png \
		images/AMBIENT_OFF_OFF.png \
		images/Settings.png \
		images/ON_ON.png \
		images/ambient_low_on.png \
		images/Navi_office.png \
		images/AMBIENT_RED_ON.png \
		images/bg_mountain.png \
		images/after.png \
		images/delete.png \
		images/HIGH_ON.png \
		images/headlamp_preview_on.png \
		images/stop.png \
		images/ON_OFF.png \
		images/tempdown_button.png \
		images/mute.png \
		images/MEDIUM_OFF.png \
		images/pause.png \
		images/Ambient_neon.png \
		images/Aircon_neon.png \
		images/Aircon.png \
		images/HIGH_OFF.png \
		images/AMBIENT_RAINBOW_OFF.png \
		images/LOW_ON.png \
		images/bg_wood.png \
		images/WINDOW_OPEN.png \
		images/Navi.png \
		images/AMBIENT_ON_ON.png \
		images/tempup_button.png \
		images/Trunk_neon.png \
		images/ambient_high_on.png \
		images/ambient_medium_off.png \
		images/bg_galaxy.png \
		images/Video.png \
		images/Checkbox_off.png \
		images/Window.png \
		images/AMBIENT_OFF_ON.png \
		images/Play_icon.png \
		images/AMBIENT_YELLOW_ON.png \
		images/Video_neon.png \
		images/Headlamp_neon.png \
		images/headlamp_preview_off.png \
		images/Bluetooth_neon.png \
		images/ambient_high_off.png \
		images/Bluetooth.png \
		images/AMBIENT_YELLOW_OFF.png \
		images/AMBIENT_RAINBOW_ON.png \
		images/ambient_medium_on.png \
		images/Ambient.png \
		images/ambient_low_off.png \
		images/page_background.png \
		images/Trunk.png \
		alert/warning.wav \
		fonts/NotoEmoji-Regular.ttf \
		account/images/Bob.png \
		account/images/Graph.png \
		account/images/killer.png \
		account/images/who.png \
		account/images/Angry.png \
		account/images/Sheep.png \
		account/images/Rabbit.png \
		account/images/Robot.png \
		gif/aircon_high_gif.gif \
		gif/window_open_gif.gif \
		gif/aircon_medium_gif.gif \
		gif/aircon_low_gif.gif \
		gif/aircon_fan.png \
		gif/window_close_gif.gif
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_accountselectpage.cpp moc_ambient_preview.cpp moc_mainwindow.cpp moc_maincontainer.cpp moc_notificationbanner.cpp moc_ripplewidget.cpp moc_mapview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_accountselectpage.cpp moc_ambient_preview.cpp moc_mainwindow.cpp moc_maincontainer.cpp moc_notificationbanner.cpp moc_ripplewidget.cpp moc_mapview.cpp
moc_accountselectpage.cpp: account/accountselectpage.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include account/accountselectpage.h -o moc_accountselectpage.cpp

moc_ambient_preview.cpp: ambient_preview.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include ambient_preview.h -o moc_ambient_preview.cpp

moc_mainwindow.cpp: system_status.h \
		ripplewidget.h \
		update_handler.h \
		mainwindow.h \
		notificationbanner.h \
		mapview.h \
		mainwindow.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_maincontainer.cpp: maincontainer.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include maincontainer.h -o moc_maincontainer.cpp

moc_notificationbanner.cpp: notificationbanner.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include notificationbanner.h -o moc_notificationbanner.cpp

moc_ripplewidget.cpp: ripplewidget.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include ripplewidget.h -o moc_ripplewidget.cpp

moc_mapview.cpp: mapview.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/moc $(DEFINES) -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/j/work/qt-navi/d3-navi -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimediaWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtMultimedia -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtWidgets -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtGui -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtNetwork -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtSql -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/qt5/QtCore -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/x86_64-oesdk-linux/lib/aarch64-telechips-linux/gcc/aarch64-telechips-linux/9.2.1/include-fixed -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1 -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/aarch64-telechips-linux -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include/c++/9.2.1/backward -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/lib/aarch64-telechips-linux/9.2.1/include -I/usr/local/qt_append/sysroots/aarch64-telechips-linux/usr/include mapview.h -o moc_mapview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_accountselectpage.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_accountselectpage.h ui_mainwindow.h
ui_accountselectpage.h: account/accountselectpage.ui
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/uic account/accountselectpage.ui -o ui_accountselectpage.h

ui_mainwindow.h: mainwindow.ui \
		maincontainer.h \
		ambient_preview.h
	/usr/local/qt_append/sysroots/x86_64-oesdk-linux/usr/bin/qt5/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

accountselectpage.o: account/accountselectpage.cpp account/accountselectpage.h \
		ui_accountselectpage.h \
		account/random_compat.h \
		db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountselectpage.o account/accountselectpage.cpp

aircon_page.o: aircon_page.cpp aircon_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aircon_page.o aircon_page.cpp

ambient_page.o: ambient_page.cpp ambient_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ambient_page.o ambient_page.cpp

ambient_preview.o: ambient_preview.cpp ambient_preview.h \
		account/random_compat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ambient_preview.o ambient_preview.cpp

db.o: db/db.cpp db/db.h \
		system_status.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db.o db/db.cpp

headlamp_page.o: headlamp_page.cpp trunk_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headlamp_page.o headlamp_page.cpp

home_page.o: home_page.cpp home_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o home_page.o home_page.cpp

main.o: main.cpp mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		account/accountselectpage.h \
		db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h \
		account/accountselectpage.h \
		db/db.h \
		aircon_page.h \
		ambient_page.h \
		window_page.h \
		headlamp_page.h \
		trunk_page.h \
		music_page.h \
		video_page.h \
		settings_page.h \
		home_page.h \
		navi_page.h \
		navi_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

maincontainer.o: maincontainer.cpp maincontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maincontainer.o maincontainer.cpp

music_page.o: music_page.cpp music_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o music_page.o music_page.cpp

notificationbanner.o: notificationbanner.cpp notificationbanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notificationbanner.o notificationbanner.cpp

ripplewidget.o: ripplewidget.cpp ripplewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ripplewidget.o ripplewidget.cpp

settings_page.o: settings_page.cpp maincontainer.h \
		settings_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h \
		db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings_page.o settings_page.cpp

trunk_page.o: trunk_page.cpp trunk_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trunk_page.o trunk_page.cpp

update_handler.o: update_handler.cpp update_handler.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h \
		aircon_page.h \
		ambient_page.h \
		headlamp_page.h \
		ambient_preview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update_handler.o update_handler.cpp

video_page.o: video_page.cpp video_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_page.o video_page.cpp

window_page.o: window_page.cpp window_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window_page.o window_page.cpp

mapview.o: mapview.cpp mapview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapview.o mapview.cpp

navi_page.o: navi_page.cpp navi_page.h \
		mainwindow.h \
		system_status.h \
		ripplewidget.h \
		update_handler.h \
		notificationbanner.h \
		mapview.h \
		ui_mainwindow.h \
		navi_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navi_page.o navi_page.cpp

navi_utils.o: navi_utils.cpp navi_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navi_utils.o navi_utils.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_accountselectpage.o: moc_accountselectpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountselectpage.o moc_accountselectpage.cpp

moc_ambient_preview.o: moc_ambient_preview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ambient_preview.o moc_ambient_preview.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_maincontainer.o: moc_maincontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maincontainer.o moc_maincontainer.cpp

moc_notificationbanner.o: moc_notificationbanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notificationbanner.o moc_notificationbanner.cpp

moc_ripplewidget.o: moc_ripplewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ripplewidget.o moc_ripplewidget.cpp

moc_mapview.o: moc_mapview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapview.o moc_mapview.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin || mkdir -p $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Telli_IVI_GUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

